# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.utils import util


class Nonce(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nonce=None):  # noqa: E501
        """Nonce - a model defined in OpenAPI

        :param nonce: The nonce of this Nonce.  # noqa: E501
        :type nonce: str
        """
        self.openapi_types = {
            'nonce': str
        }

        self.attribute_map = {
            'nonce': 'nonce'
        }

        self._nonce = nonce

    @classmethod
    def from_dict(cls, dikt) -> 'Nonce':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The nonce of this Nonce.  # noqa: E501
        :rtype: Nonce
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nonce(self):
        """Gets the nonce of this Nonce.


        :return: The nonce of this Nonce.
        :rtype: str
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce):
        """Sets the nonce of this Nonce.


        :param nonce: The nonce of this Nonce.
        :type nonce: str
        """

        self._nonce = nonce
