# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.utils import util


class Vnfd(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None):  # noqa: E501
        """Vnfd - a model defined in OpenAPI

        :param id: The id of this Vnfd.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {"id": str}

        self.attribute_map = {"id": "id"}

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> "Vnfd":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The vnfd of this Vnfd.  # noqa: E501
        :rtype: Vnfd
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Vnfd.


        :return: The id of this Vnfd.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Vnfd.


        :param id: The id of this Vnfd.
        :type id: str
        """

        self._id = id
