name: "Pull Request Docs Check"
on: 
- pull_request
- workflow_dispatch


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sphinx
      run: |
        cd docs
        pip install -r requirements.txt
        sphinx-build -b html ./source ./build
    - name: Push to gh-page
      uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build/
