name: "Pull Request Docs Check"
on: 
- pull_request
- workflow_dispatch


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sphinx
      run: |
        cd docs
        pip install -r requirements.txt
        sphinx-build -b html ./source ./build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
